/**
 * `npm run context:render` - print a REAL assembled context.
 *
 * Three audiences, one command:
 *
 *  - `CONVERSATION_CONTEXT.md` quotes this output verbatim. A worked example in
 *    documentation that was typed by hand is a worked example that is wrong by
 *    the second commit; this one is generated by the code it documents.
 *  - `MISSION-2-LOCAL-BRAIN-AUTO-EVAL` needs the exact prompt text a candidate
 *    model will see, so the benchmark measures this context rather than a toy
 *    one. `--json` emits the whole `AssembledContext`.
 *  - Anyone tuning the budget. `--sizes` prints where every character goes,
 *    which is the only way to have an informed argument about `num_ctx`.
 *
 * It seeds a throwaway database with a two-session world: a completed earlier
 * conversation with durable facts and a recorded call outcome, a promised
 * callback, a qualification with gaps in it, and a live second conversation.
 * That is the interesting case - a returning contact - and it is the one worth
 * putting in front of a reviewer.
 *
 * Flags: `--json`, `--sizes`, `--terse` (a tiny facts budget, to show the
 * reduction ladder working).
 */
import { llmToolDefinitions, TOOL_NAMES } from '../agent/tools/definitions.js';
import { buildSystemPrompt, LOCAL_BRAIN_SYSTEM_PROMPT_REF } from '../agent/prompt/systemPrompt.js';
import { seedSliceWorld } from '../app/seedSliceWorld.js';
import { ConversationContextAssembler } from '../conversation/contextAssembler.js';
import { serializeConversationMemory } from '../conversation/conversationMemory.js';
import { defaultBusinessProfile } from '../context/businessProfile.js';
import { scoreQualification } from '../agent/tools/qualificationRubric.js';
import { FutureActionService } from '../followup/futureActionService.js';
import { createProviderRegistry } from '../providers/index.js';
import { SchedulingValidator } from '../scheduling/schedulingValidator.js';
import { stringifyJson } from '../shared/json.js';
import { measureFixedOverheadChars, withTemporaryDatabase } from './support.js';

async function main(): Promise<void> {
  const asJson = process.argv.includes('--json');
  const showSizes = process.argv.includes('--sizes');
  const terse = process.argv.includes('--terse');

  await withTemporaryDatabase(async ({ db, clock }) => {
    const world = await seedSliceWorld(db, { contactIsDecisionMaker: false });
    const overhead = measureFixedOverheadChars();

    await db.contacts.update(world.contact.id, {
      notes: 'Runs operations for a family HVAC business; prefers a call to an email.',
    });
    await db.leads.create({
      organizationId: world.organization.id,
      contactId: world.contact.id,
      source: 'inbound_web_form',
      status: 'QUALIFYING',
    });

    // ---- session one, three weeks ago, finished -------------------------
    const first = await db.conversations.create({
      organizationId: world.organization.id,
      contactId: world.contact.id,
      aiAgentId: world.aiAgent.id,
      agentConfigurationId: world.agentConfiguration.id,
      channel: 'VOICE',
      status: 'COMPLETED',
      startedAt: '2026-02-11T15:10:00.000Z',
    });
    await db.conversations.update(first.id, {
      status: 'COMPLETED',
      endedAt: '2026-02-11T15:26:00.000Z',
      summary: serializeConversationMemory({
        narrative:
          'A first conversation three weeks ago. The contact described running fourteen technicians off a ' +
          'whiteboard and a shared calendar, and said same-day reschedules were costing them a job or two a ' +
          'week. They asked how Northwind would handle their QuickBooks setup and never got a full answer ' +
          'before they had to go. They were clear that nothing would change during the summer peak.',
        durableFacts: [
          { id: 'crew_size', fact: 'They run fourteen field technicians across two vans and one truck.' },
          { id: 'current_process', fact: 'Scheduling today is a whiteboard in the office plus a shared calendar.' },
          { id: 'accounting_system', fact: 'They run QuickBooks Online.' },
          { id: 'pain_point', fact: 'Same-day reschedules cost them roughly one or two jobs a week.' },
          { id: 'seasonality', fact: 'They will not change systems during the summer peak, June to August.' },
          { id: 'decision_maker', fact: 'Their brother co-owns the business and signs for anything over a few thousand.' },
        ],
        unresolvedTopics: [
          { id: 'quickbooks_sync_detail', topic: 'How the QuickBooks Online sync handles their existing job codes', raisedBy: 'CONTACT' },
          { id: 'budget_today', topic: 'What they currently spend on software for the field', raisedBy: 'AGENT' },
        ],
        coveredThroughTurnIndex: 11,
        generatedBy: 'local-brain-demo',
        generatedAtUtc: '2026-02-11T15:26:00.000Z',
      }),
    });

    const call = await db.calls.create({
      organizationId: world.organization.id,
      contactId: world.contact.id,
      conversationId: first.id,
      direction: 'OUTBOUND',
      providerName: 'conversation',
      status: 'COMPLETED',
      startedAt: '2026-02-11T15:10:00.000Z',
      endedAt: '2026-02-11T15:26:00.000Z',
    });
    await db.callOutcomes.upsertForCall({
      callId: call.id,
      outcome: 'CONNECTED',
      notes: 'Ran out of time mid-question about QuickBooks. Asked to be picked up again in March.',
      recordedByToolCallId: null,
    });

    // ---- what we promised, and it is saved -------------------------------
    // Scheduled through the REAL FutureActionService rather than inserted, for
    // two reasons. `FutureAction.validationProvenanceJson` is NOT NULL and
    // structurally checked on write, so a hand-made row is refused - which is
    // the schema working. And a rendered example whose "promised callback"
    // never went through validation would be showing something this system
    // cannot actually produce.
    const followups = new FutureActionService({
      db,
      clock,
      validator: new SchedulingValidator({ clock, availability: createProviderRegistry({}).availability }),
    });
    const promised = await followups.schedule({
      organizationId: world.organization.id,
      contactId: world.contact.id,
      conversationId: first.id,
      agentConfigurationId: world.agentConfiguration.id,
      // The contact's own words, as every time-bearing path in this codebase
      // requires. Friday 11:00 in America/New_York, resolved by application code.
      proposal: { raw: 'Friday at 11am', timezone: world.contact.timezone },
      nowUtc: clock.nowUtc(),
      reason: 'Contact asked to pick the conversation up again in March.',
      correlationId: 'render-example',
      toolCallId: 'render-example-call',
    });
    if (!promised.ok) {
      throw new Error(`The rendering example could not schedule its callback: ${promised.reason}`);
    }

    // ---- qualification, with real gaps in it ----------------------------
    const scoring = scoreQualification({
      observations: [
        { factor: 'need_established', value: 80, evidence: 'Same-day reschedules cost them one or two jobs a week.' },
        { factor: 'engagement', value: 70, evidence: 'Stayed on the call sixteen minutes and asked about QuickBooks.' },
      ],
      isDecisionMaker: false,
    });
    await db.qualificationStates.upsertForContact({
      contactId: world.contact.id,
      score: scoring.score,
      rawScore: scoring.rawScore,
      cappedScore: scoring.cappedScore,
      band: scoring.band,
      isDecisionMaker: scoring.isDecisionMaker,
      rubricVersion: scoring.rubricVersion,
      factorsJson: stringifyJson({ factors: scoring.factors }),
      updatedByToolCallId: null,
    });

    // ---- session two, today ----------------------------------------------
    const second = await db.conversations.create({
      organizationId: world.organization.id,
      contactId: world.contact.id,
      aiAgentId: world.aiAgent.id,
      agentConfigurationId: world.agentConfiguration.id,
      channel: 'VOICE',
      status: 'ACTIVE',
      startedAt: clock.nowUtc(),
    });
    for (const [role, text] of [
      ['AGENT', 'Morning - it is Avery from Northwind, we spoke a few weeks back about the whiteboard.'],
      ['CONTACT', 'Oh right, yes. Sorry, it has been chaos here. What was it you wanted?'],
      ['AGENT', 'No trouble at all. You had a question about QuickBooks we never got to the bottom of.'],
      ['CONTACT', 'That is right. And honestly, before any of that - what does this actually cost?'],
    ] as const) {
      await db.conversationTurns.appendTurn({ conversationId: second.id, role, text, createdAt: clock.nowUtc() });
    }

    // ---- assemble ---------------------------------------------------------
    const assembler = new ConversationContextAssembler({
      db,
      clock,
      businessProfile: defaultBusinessProfile(),
      ...(terse ? { budget: { maxFactsChars: 2600, minFactsChars: 2600 } } : {}),
    });
    const assembled = await assembler.assemble({
      conversationId: second.id,
      fixedOverheadChars: overhead.total,
    });

    if (asJson) {
      console.log(stringifyJson(assembled));
      return;
    }

    if (showSizes) {
      const prompt = buildSystemPrompt({ promptRef: LOCAL_BRAIN_SYSTEM_PROMPT_REF, allowedToolNames: [...TOOL_NAMES] });
      const budget = assembled.budget;
      const perToken = budget.config.charsPerToken;
      const row = (label: string, chars: number) =>
        `  ${label.padEnd(34, '.')} ${String(chars).padStart(7)} chars  ~${String(Math.round(chars / perToken)).padStart(6)} tok`;

      console.log('where every character of a turn goes');
      console.log('='.repeat(78));
      console.log(row(`system prompt (${prompt.composition.ref})`, prompt.text.length));
      console.log(row(`tool schemas (${TOOL_NAMES.length} tools)`, JSON.stringify(llmToolDefinitions([...TOOL_NAMES])).length));
      console.log(row('  = fixed overhead', overhead.total));
      console.log(row('reserved for the reply', budget.reservedForResponseChars));
      console.log(row('assembled background (actual)', assembled.rendered.text.length));
      console.log(row('  its budget', budget.factsBudgetChars));
      console.log(row('transcript window (actual)', assembled.facts.transcript.charCount));
      console.log(row('  its budget', budget.transcriptBudgetChars));
      console.log(
        row('TOTAL USED', overhead.total + assembled.rendered.text.length + assembled.facts.transcript.charCount),
      );
      console.log(row(`CEILING (num_ctx ${budget.config.modelNumCtx})`, budget.totalChars));
      console.log('');
      console.log(`  reductions applied: ${assembled.reductionsApplied.join(' -> ') || '(none - everything fitted)'}`);
      console.log(`  hard truncated    : ${assembled.hardTruncated}`);
      console.log(`  transcript floor  : ${budget.transcriptFloorApplied}`);
      console.log('='.repeat(78));
      return;
    }

    console.log(assembled.rendered.text);
  });
}

main().catch((error: unknown) => {
  console.error('\ncontext:render FAILED\n');
  console.error(error);
  process.exitCode = 1;
});
