/**
 * Identifier generation.
 *
 * Row primary keys are generated by Prisma (`@default(cuid())`). The ids
 * generated here are the ones application code must mint itself:
 *
 *  - correlationId  - ties every audit event of one agent turn together
 *  - toolCallId     - a fallback when the LLM provider does not supply one
 *  - idempotencyKey - makes a retried tool call a no-op instead of a duplicate
 *
 * `IdGenerator` exists so tests can inject a deterministic sequence, exactly as
 * `Clock` does for time. Never call the module-level functions from inside
 * business logic that a test needs to be deterministic - inject instead.
 */
import { randomUUID } from 'node:crypto';

import { stringifyJsonStable } from './json.js';

export interface IdGenerator {
  /** A fresh, globally unique opaque id. */
  newId(): string;
}

export class RandomIdGenerator implements IdGenerator {
  newId(): string {
    return randomUUID();
  }
}

/** Deterministic generator for tests: `prefix-1`, `prefix-2`, ... */
export class SequentialIdGenerator implements IdGenerator {
  private counter = 0;

  constructor(private readonly prefix = 'id') {}

  newId(): string {
    this.counter += 1;
    return `${this.prefix}-${this.counter}`;
  }
}

/** A correlation id for one agent turn. Human-greppable on purpose. */
export function newCorrelationId(): string {
  return `corr_${randomUUID()}`;
}

/** A tool call id, used when the provider did not supply one. */
export function newToolCallId(): string {
  return `tool_${randomUUID()}`;
}

/**
 * Derive a stable idempotency key from the semantic identity of an action.
 *
 * Two attempts that mean the same thing must produce the same key, so that the
 * `@unique` columns on Meeting.idempotencyKey / FutureAction.idempotencyKey can
 * turn a retry into a conflict instead of a duplicate row.
 */
export function deriveIdempotencyKey(namespace: string, parts: Record<string, unknown>): string {
  return `${namespace}:${stringifyJsonStable(parts)}`;
}
