/**
 * ONE definition of "this text is a line of dialogue, not a fact".
 *
 * WHY THIS FILE EXISTS
 * ---------------------------------------------------------------------------
 * The governing rule of this mission is that customer-facing wording must be
 * generated by the model, never selected from text an engineer wrote. That rule
 * has two places it can be broken:
 *
 *   1. In DATA - somebody writes `"Great, let me get that booked for you!"`
 *      into the business profile and the model reads it back verbatim.
 *   2. In CODE - somebody writes `if (state === X) return "..."` in the
 *      customer-facing path.
 *
 * Both are the same mistake, so both are checked against the same rule set,
 * defined here exactly once:
 *
 *   - `BusinessProfileSchema` (src/context/businessProfile.ts) runs it over
 *     every free-text string in a profile at LOAD time, so a profile carrying
 *     a scripted line fails to load at all.
 *   - `npm run check:anti-scripting` (src/context/antiScriptingCheck.ts) runs a
 *     superset of it over `src/agent/**`, `src/conversation/**` and
 *     `src/context/**`.
 *
 * WHAT THIS CAN AND CANNOT DO - STATED HONESTLY
 * ---------------------------------------------------------------------------
 * It catches text that is SHAPED like an instruction to say something, or like
 * a quoted utterance. It cannot catch a declarative sentence that a determined
 * author intends to be read out verbatim, because "Our onboarding takes two
 * weeks" is a legitimate fact AND a usable sentence, and no regular expression
 * can tell the author's intent apart. The defence against that is the rendering
 * frame (facts are rendered under an explicit "these are facts, not sentences
 * to say" heading) plus review. `CONVERSATION_CONTEXT.md` says so in the same
 * words rather than implying the check is complete.
 */

/** A rule that recognises one shape of dialogue-as-data. */
export interface DialogueShapeRule {
  /** Stable id. Reports name this, never the regex. */
  readonly id: string;
  /** Why this shape is forbidden, in a sentence a reviewer can act on. */
  readonly why: string;
  readonly pattern: RegExp;
}

/**
 * The rules, in the order they are tried.
 *
 * Every pattern is deliberately narrow. A false positive here blocks a
 * legitimate fact from being written down, which pushes an author towards
 * putting the fact somewhere worse - so the bar for adding a rule is that it
 * catches a real scripting pattern and nothing else.
 */
export const DIALOGUE_SHAPE_RULES: readonly DialogueShapeRule[] = [
  {
    id: 'IMPERATIVE_TO_SPEAK',
    why:
      'Begins by instructing the agent to utter something. A profile supplies facts the model may use; ' +
      'it never supplies the words, and it never dictates when they are used.',
    pattern:
      /^\s*(?:always\s+|never\s+|then\s+|first\s+|next\s+|finally\s+)?(?:say|tell|ask|reply|respond|answer|greet|pitch|open\s+with|close\s+with|lead\s+with|start\s+by|begin\s+by|follow\s+up\s+with|push\s+back\s+with|counter\s+with)\b/i,
  },
  {
    id: 'ADDRESSED_SPEECH_INSTRUCTION',
    why:
      'Instructs the agent to direct specific speech at the contact. The model decides how to communicate ' +
      'a fact; data does not decide it for them.',
    pattern:
      /\b(?:say|said|tell|telling|reply|replying|respond|responding|answer)\s+(?:this\s+|that\s+|it\s+)?(?:to\s+)?(?:them|him|her|the\s+(?:contact|customer|prospect|caller|lead|client))\b/i,
  },
  {
    id: 'SHOULD_SAY',
    why: 'A prescribed utterance. The rule this mission is built on forbids prewritten customer-facing wording.',
    pattern: /\b(?:should|must|needs?\s+to|ought\s+to|has\s+to|have\s+to)\s+(?:always\s+|never\s+)?(?:say|reply|respond|answer|repeat|read\s+out)\b/i,
  },
  {
    id: 'IF_THEY_THEN_SAY',
    why:
      'An if-X-then-say-Y branch. This is a conversation tree written in prose, and it is the exact pattern ' +
      'the Founder directive names.',
    pattern:
      /\b(?:if|when|whenever)\b[^.!?]{0,120}?\b(?:then\s+)?(?:say|reply|respond|answer|tell\s+them|use\s+the\s+line|use\s+this\s+line)\b/i,
  },
  {
    id: 'QUOTED_UTTERANCE',
    why:
      'A quoted sentence long enough to be read out verbatim. Quoting the CONTACT is fine in a transcript, ' +
      'but a profile or a code constant has no contact to quote - so a quotation here is a script.',
    // Four or more words inside quotes, ending in sentence punctuation or a
    // closing quote. Short quoted terms ("Pro", "per seat") stay legal.
    pattern: /["“][^"”]*?\b\w+\b[^"”]*?\b\w+\b[^"”]*?\b\w+\b[^"”]*?\b\w+\b[^"”]*?["”]/,
  },
  {
    id: 'SCRIPT_VOCABULARY',
    why:
      'Names a scripted artefact. If a profile needs a "script", a "rebuttal" or a "closing line", the thing ' +
      'it is describing is forbidden however it is spelled.',
    pattern: /\b(?:sales\s+script|call\s+script|scripted\s+(?:reply|response|line|answer)|rebuttal|closing\s+line|opening\s+line|talk\s+track|word\s+track)\b/i,
  },
];

export interface DialogueShapeFinding {
  readonly ruleId: string;
  readonly why: string;
  /** The exact substring that matched, for a report a human can act on. */
  readonly matched: string;
}

/**
 * The first rule `text` violates, or `null` when it is shaped like a fact.
 *
 * First-match rather than all-matches on purpose: one clear reason is more
 * actionable than six overlapping ones, and an author fixing the text will
 * re-run the check anyway.
 */
export function findDialogueShape(text: string): DialogueShapeFinding | null {
  for (const rule of DIALOGUE_SHAPE_RULES) {
    const match = rule.pattern.exec(text);
    if (match) {
      return { ruleId: rule.id, why: rule.why, matched: match[0] };
    }
  }
  return null;
}

/** Convenience predicate for a Zod refinement. */
export function isFactShaped(text: string): boolean {
  return findDialogueShape(text) === null;
}
